config:
  send_anonymous_usage_stats: False

cat_predict_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: dbt
      pass: password1234
      dbname: hass_db
      schema: hass_schema
